### ISSUE TITLE
FartherViewDistance doesn't work

### ISSUE THREAD

**Issue by wicivo** [RealTriassic/LinearPaper#12] opened 2024-06-28 07:25 UTC
```
[13:07:42 ERROR]: Error occurred while enabling FartherViewDistance v9.9.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/nbt/Tag
        at FartherViewDistance.jar/xuan.cat.fartherviewdistance.code.branch.v121.Branch_121_Packet.<init>(Branch_121_Packet.java:24) ~[FartherViewDistance.jar:?]
        at FartherViewDistance.jar/xuan.cat.fartherviewdistance.code.ChunkIndex.onEnable(ChunkIndex.java:124) ~[FartherViewDistance.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[linearpaper-1.21.jar:1.21-DEV-b44029b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[linearpaper-1.21.jar:1.21-DEV-b44029b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[linearpaper-1.21.jar:1.21-DEV-b44029b]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[linearpaper-1.21.jar:1.21-DEV-b44029b]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:328) ~[linearpaper-1.21.jar:1.21-DEV-b44029b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[linearpaper-1.21.jar:1.21-DEV-b44029b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[linearpaper-1.21.jar:1.21-DEV-b44029b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.nbt.Tag
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 14 more
```

**Comment by RealTriassic** [comment] 2024-06-28 11:46
Have you tried running the plugin on Paper 1.21? I feel like this might be a case of the plugin not being updated to 1.21 rather than something caused by LinearPaper

**Comment by wicivo** [comment] 2024-06-28 11:47
> Have you tried running the plugin on Paper 1.21? I feel like this might be a case of the plugin not being updated to 1.21 rather than something caused by LinearPaper

yes

**Comment by wicivo** [comment] 2024-06-28 11:47
I tested it on paper 1.21

**Comment by wicivo** [comment] 2024-06-28 11:49
https://github.com/EuSouVoce/FartherViewDistance_1.20.1

**Comment by RealTriassic** [comment] 2024-06-28 11:50
Okay, I'll look into it and try to reproduce the issue later today

**Comment by RealTriassic** [comment] 2024-06-28 13:34
Fixed by https://github.com/StupidCraft/LinearPaper/commit/9ae08cb4c11de65b15e91858f132c8f1224a8775 (for 1.20.6) and https://github.com/StupidCraft/LinearPaper/commit/ba85a7bdf81c952a5728547e209d5ec2487bd9b2 (for 1.21).

**Closed as completed by RealTriassic** 2024-06-28 13:34 UTC
